site_name: Xepher Skirmish Club
site_url: https://xepher.adelynflowers.dev
theme:
  name: material
  palette:
    primary: "deep purple"

plugins:
  - search
extra:
  social:
    - icon: fontawesome/brands/discord
      name: Xepher Arcade Discord
      link: https://discord.gg/xepherarcade
